sudo: false
language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
    - python -m unittest discover test
branches:
  only:
  - master
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: AKIAISP7BT5QAO4YLMKA
  secret_access_key: &14371220
    secure: akYEEBUcrAoxiAnLfk8nIknj6kHeOXMkYQtfTgJX81eEFin6hKH5ytMZo8T7Egyap9WbxczXHZS4wYGO5wtQVKGCU6n3uJB0r59olm9e0ccfLCo1j86QlilNI18/+p9obw+lcSi8rY4n6yGdH0bZfEaz4w+pweATBcQt1l3VbM5ZohCHCWmkDqvgUBn8AxrkYY+IIwCFrZvocyIM6B4fvZtDcYiWNyfAU+TW6Binz7XKldTHQTdWz4mWP17g31BJlEvQTmQ4GC0RxsJijFTOKdUhhMY1pjlR0wX8xIlyW+53MSwt1bOIcCWivpHfzdc3EdrQLd/moJ+2z/j7nQIg7qKnbx2Vw8ECLA5DWQUhbi08nLyMha9hE+0gCOGMtLOfrQAUEE/VUZ9VLluggNNxSnF4wYrekTFeKf/z+xVM+Q97Cu4uH9edyC0Cwxnng8P8wDciBUApj2kZMThW+Y9rX1IQA0fAK00IH6/Uz1dVLSBVYNDN5QuEZ/5euRIRcL/pqngbiaPeHQLhdNJ7mThg6+DIZV8OZTrWmCFr4ivIOu6xEno4Fx/gfxNmUAD2QRWWkOgYTTHrwl2LcSC3LE1MNCPbrFcux0FP6ekaWObmPaIHn+VlxBfdyUDyLSgIYsCe3qKwYqtTMv0lfPbKi5XMeW2Gll/4n6XpfIVltnzu00c=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &12841200
    repo: tobwilk/flaskr
  bucket: flaskr-codedeploy
  region: eu-west-1
- provider: codedeploy
  access_key_id: AKIAISP7BT5QAO4YLMKA
  secret_access_key: *14371220
  bucket: flaskr-codedeploy
  key: latest.zip
  bundle_type: zip
  application: flaskr
  deployment_group: flaskr
  on: *12841200
  region: eu-west-1
